### ISSUE TITLE
created events fired on edit?

### ISSUE THREAD

**Issue by themightychris** [rcfox/Discourse-Webhooks#2]
the post_created and topic_created webhooks seem to fire repeatedly each time an attribute of either gets edited. I'm trying to filter them out client-side right now but I'm wondering if there's any improvement to be made here in the plugin?

**Comment by themightychris** [comment]
I've also been seeing the topic_created event getting fired every few days for the introduction topic which we deleted. Anyone know anything about why that might be that could help me either fix the plugin or filter out the extra events?

**Comment by rcfox** [comment]
Whoops, I was putting off commenting on this because I didn't notice it was on Github. (I assumed it was on the Discourse forums.)

I'm not sure that this kind of filtering belongs in the plugin, it sounds like Discourse itself is misbehaving. It might be good to talk to the Discourse developers to see if this behaviour is intentional. https://meta.discourse.org/
